2023-05-19 18:16:57,978 - ERROR - Ошибка: HTTPConnectionPool(host='vps1.example.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002DCF7DDD0D0>: Failed to resolve 'vps1.example.com' ([Errno 11001] getaddrinfo failed)"))
2023-05-19 18:16:57,984 - ERROR - Произошла ошибка на VPS: http://vps1.example.com
2023-05-19 18:16:57,984 - ERROR - Ошибка: HTTPConnectionPool(host='vps1.example.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002DCF7DDEF50>: Failed to resolve 'vps1.example.com' ([Errno 11001] getaddrinfo failed)"))
